name: Run Workflow to Deploy Code

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (dev, qa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install yq (to read YAML files)
      - name: Install yq
        run: |
          sudo apt-get update
          sudo snap install yq --classic  # Install yq via snap (v4.x compatible)

      # Step 3: Load environment configuration based on the input environment
      - name: Load environment configuration
        id: load_config
        run: |
          # Use the environment input to directly load the correct config file
          CONFIG_FILE="env/${{ github.event.inputs.environment }}.yml"

          # Check if the selected environment file exists
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file $CONFIG_FILE does not exist!"
            exit 1
          fi

          # Print the environment and DB details
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "DB Host: $(yq e '.db.host' $CONFIG_FILE)"
          echo "DB Port: $(yq e '.db.port' $CONFIG_FILE)"
          echo "DB Username: $(yq e '.db.username' $CONFIG_FILE)"
          echo "DB Password: $(yq e '.db.password' $CONFIG_FILE)"
          echo "DB Name: $(yq e '.db.database' $CONFIG_FILE)"
