name: Run Workflow to Deploy Code

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (dev, qa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  Load_Environment_Data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install yq (to read YAML files)
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq  # Install jq first (required for parsing JSON in some cases)
          sudo snap install yq --classic  # Install yq via snap (v4.x compatible)

      # Step 3: Load environment configuration based on the input environment
      - name: Load environment configuration
        id: load_config
        run: |
          # Use the environment input to directly load the correct config file
          CONFIG_FILE="env/${{ github.event.inputs.environment }}.yml"

          # Check if the selected environment file exists
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file $CONFIG_FILE does not exist!"
            exit 1
          fi

          # Read DB details from the YAML file using yq (v4.x syntax)
          DB_HOST=$(yq e '.db.host' $CONFIG_FILE)
          DB_PORT=$(yq e '.db.port' $CONFIG_FILE)
          DB_USERNAME=$(yq e '.db.username' $CONFIG_FILE)
          DB_PASSWORD=$(yq e '.db.password' $CONFIG_FILE)
          DB_NAME=$(yq e '.db.database' $CONFIG_FILE)

          # Print the environment and DB details
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "DB Host: $DB_HOST"
          echo "DB Port: $DB_PORT"
          echo "DB Username: $DB_USERNAME"
          echo "DB Password: $DB_PASSWORD"
          echo "DB Name: $DB_NAME"
