name: Dynamic Folder Dropdown Example

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Choose a folder'
        required: true
        type: choice
        options: []  # Placeholder for dynamic options - will be populated manually

jobs:
  list_folders:
    runs-on: ubuntu-latest
    outputs:
      folder_list: ${{ steps.get_folders.outputs.folder_list }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Folders
        id: get_folders
        run: |
          # Find all directories at the root of the repo, excluding .git and hidden files
          folders=$(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path './.git' -exec basename {} \;)
          
          # Store the folder list in the output
          echo "::set-output name=folder_list::$folders"
          echo "Found folders: $folders"

      - name: Save Folder List as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: folder-list
          path: folder_list.txt

  # You can add another job to process the folder based on user input
  process_folder:
    needs: list_folders
    runs-on: ubuntu-latest
    steps:
      - name: Download Folder List
        uses: actions/download-artifact@v3
        with:
          name: folder-list

      - name: Process Folder Based on Input
        run: |
          echo "You selected the folder: ${{ github.event.inputs.folder }}"
