name: List Folders

on:
  workflow_dispatch:

jobs:
  list_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List all folders
        id: get_folders
        run: |
          # Find all directories at the root of the repository (ignoring hidden files and .git)
          folders=$(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path './.git' -exec basename {} \; | grep -v '^.$')
          
          # Output the list of folders
          echo "Folders found: $folders"
          
          # Save the folder list to an output
          echo "::set-output name=folder_list::$folders"

      - name: Display the Folder List
        run: |
          # Display the folder list output
          echo "The folders are: ${{ steps.get_folders.outputs.folder_list }}"
