name: Dynamic Deployment with Separate Files

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Determine environment file
      id: determine-env
      run: |
        branch="${{ github.ref_name }}"
        echo "Branch: $branch"

        # Set the config file path dynamically based on the branch
        CONFIG_FILE="env-configs/${branch}.json"
        echo "Config File: $CONFIG_FILE"

        if [[ ! -f "$CONFIG_FILE" ]]; then
          echo "Error: Config file for branch '$branch' not found at '$CONFIG_FILE'."
          exit 1
        fi

        echo "CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV

    - name: Load environment variables from file
      id: load-env
      run: |
        # Read the environment file
        ENV_VARS=$(cat ${{ env.CONFIG_FILE }})
        echo "Environment Variables: $ENV_VARS"

        # Parse variables using jq
        ENV_NAME=$(echo "$ENV_VARS" | jq -r '.ENV_NAME')
        API_URL=$(echo "$ENV_VARS" | jq -r '.API_URL')

        # Export them as GitHub environment variables
        echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
        echo "API_URL=$API_URL" >> $GITHUB_ENV
