name: Print Environment Data

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (dev, qa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  print_data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install yq (to read YAML files)
      - name: Install yq
        run: sudo apt-get install yq

      # Step 3: Load environment configuration based on the input environment
      - name: Load environment configuration
        id: load_config
        run: |
          # Dynamically load the appropriate config file based on input environment
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            CONFIG_FILE="env/dev.yml"
          elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
            CONFIG_FILE="env/qa.yml"
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            CONFIG_FILE="env/prod.yml"
          else
            echo "Invalid environment specified"
            exit 1
          fi

          # Read DB details from the YAML file
          DB_HOST=$(yq eval '.db.host' $CONFIG_FILE)
          DB_PORT=$(yq eval '.db.port' $CONFIG_FILE)
          DB_USERNAME=$(yq eval '.db.username' $CONFIG_FILE)
          DB_PASSWORD=$(yq eval '.db.password' $CONFIG_FILE)
          DB_NAME=$(yq eval '.db.database' $CONFIG_FILE)

          # Print the environment and DB details
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "DB Host: $DB_HOST"
          echo "DB Port: $DB_PORT"
          echo "DB Username: $DB_USERNAME"
          echo "DB Password: $DB_PASSWORD"
          echo "DB Name: $DB_NAME"

