name: Update Main Workflow Dispatch Inputs (Selective Update)

on:
  workflow_dispatch:

jobs:
  update_workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List all folders
        id: get_folders
        run: |
          # Find all directories at the root of the repository (ignoring hidden files and .git)
          folders=$(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path './.git' -exec basename {} \; | grep -v '^.$' | tr '\n' ' ')

          # Save folder list to environment variable for later use
          echo "folders=$folders" >> $GITHUB_ENV

      - name: Prepare Folder Options for SOURCE_REGION Dropdown
        id: prepare_folder_options
        run: |
          # Prepare the dropdown options for SOURCE_REGION
          source_region_options=""
          for folder in ${{ env.folders }}; do
            source_region_options="${source_region_options}\n- ${folder}"
          done

          # Save the options as an environment variable for use in the next step
          echo "source_region_options=${source_region_options}" >> $GITHUB_ENV

      - name: Update Main Workflow YAML (only SOURCE_REGION)
        run: |
          # Path to the main workflow YAML file
          WORKFLOW_FILE=".github/workflows/main-workflow.yml"
          
          # Replace the SOURCE_REGION options with the dynamic list
          sed -i "s|  - .*$|${source_region_options//\n/\\n}|" "$WORKFLOW_FILE"

      - name: Check if the file has changed
        run: |
          # Check if the YAML file has changed
          git diff --exit-code .github/workflows/main-workflow.yml || echo "Changes detected"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Configure Git user for the commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage, commit, and push changes
          git add .github/workflows/main-workflow.yml
          git commit -m "Update SOURCE_REGION options dynamically"
          git push origin HEAD:main
